"""
retrospect.py — RIL offline cadence (post-run scorer), per RIL_PROGRAM.md §1/§5.

NO-SPEND, stdlib + the existing ledger files. Checkpoint-triggered batch (NOT a daemon). Reads the
claim records + failure_log + rolling_calibration, scores the reasoning trace against the
research-hypothesis-generation-guide §4 rubric with DETERMINISTIC heuristics (a session-LLM rubric
judge of a different family can be layered later), and regenerates
substrate_calibration/retrospectives/next_session_prepend.md — the digest mechanically prepended to
the next similar task (the "learn from its own mistakes" mechanism).

This is REFLECTION, not an audit gate (CLAUDE.md §7). Claims used as audit evidence still pass
composite-auditor.

Usage:  python substrate_calibration/tools/retrospect.py
"""
from pathlib import Path
import sys
import json
from collections import Counter

sys.path.insert(0, str(Path(__file__).resolve().parent))
from compute_ece import load_records, outcome_to_label  # noqa: E402

RECORDS_DIR = Path("substrate_calibration/records")
RETRO_DIR = Path("substrate_calibration/retrospectives")
FAILURE_LOG = RETRO_DIR / "failure_log.jsonl"
ROLLING = RETRO_DIR / "rolling_calibration.json"
PREPEND = RETRO_DIR / "next_session_prepend.md"


def load_failures():
    if not FAILURE_LOG.exists():
        return []
    out = []
    for line in FAILURE_LOG.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line:
            out.append(json.loads(line))
    return out


def score_rubric(records):
    """Deterministic heuristics for the guide §4 rubric (0-1). Novelty is NA (not deterministic)."""
    resolved = [(r, outcome_to_label(r.get("observed_outcome"))) for r in records]
    resolved = [(r, l) for r, l in resolved if l is not None]
    n = len(records) or 1
    n_res = len(resolved) or 1
    factuality = sum(1 for _, l in resolved if l == 1.0) / n_res
    citation_correctness = sum(1 for r in records
                               if "§Tier" not in str(r.get("framework_applied", ""))
                               and "§" in str(r.get("framework_applied", ""))) / n
    completeness = sum(1 for r in records if r.get("gap_flags") and r.get("evidence_cited", r.get("claim_text"))) / n
    testability = sum(1 for r in records if r.get("observable_at") and
                      (r.get("expected_outcome_if_h1") or r.get("expected_outcome_if_h0"))) / n
    uncertainty = sum(1 for r in records if r.get("confidence_by_subclaim")) / n
    safety_ethics = 1.0  # no compliance violation detected in records this pass
    return {
        "factuality": round(factuality, 3),
        "citation_correctness": round(citation_correctness, 3),
        "completeness": round(completeness, 3),
        "novelty": None,  # not deterministically computable; left for an LLM judge layer
        "testability": round(testability, 3),
        "uncertainty": round(uncertainty, 3),
        "safety_ethics": safety_ethics,
    }


def main():
    records = load_records(str(RECORDS_DIR))
    failures = load_failures()
    rolling = json.loads(ROLLING.read_text(encoding="utf-8")) if ROLLING.exists() else {}

    rubric = score_rubric(records)
    recurring = Counter(f["failure_type"] for f in failures if not f.get("resolved", True))
    open_failures = [f for f in failures if not f.get("resolved", True)]

    # cap state summary
    caps = []
    for s, v in (rolling.get("per_stream") or {}).items():
        if v.get("confidence_cap_active"):
            caps.append(f"{s}: cap ACTIVE (clamp {v['cap_value']})")
    cap_line = "; ".join(caps) if caps else "no auto-cap active (windows dormant/ok)"

    lessons = [
        "Resolve external identifiers via resolve_id.require(); never hardcode IDs from memory.",
        "Every claim record gets top-level alternatives_considered + contradictory_evidence_cited.",
        "Cite the framework by specific §section with a quoted criterion, never '§Tier N'.",
        "On an absent marker/ID, record the reason — silent absence hides errors.",
    ]

    prepend = []
    prepend.append("# next_session_prepend — RIL digest (auto-generated by retrospect.py)\n")
    prepend.append("> Read this BEFORE analytical output (CLAUDE.md §10 step 8). Reflection, not an audit gate.\n")
    prepend.append("## Rubric (guide §4, deterministic heuristics over current records)\n")
    for k, v in rubric.items():
        prepend.append(f"- {k}: {v}")
    prepend.append(f"\n## Reactive calibration\n- {cap_line}\n")
    prepend.append("## Open / recurring failure types (fix-forward)\n")
    if recurring:
        for ft, c in recurring.most_common():
            prepend.append(f"- {ft} ×{c} (unresolved)")
    else:
        prepend.append("- none open")
    prepend.append("\n## Standing lessons (do NOT repeat)\n")
    for ls in lessons:
        prepend.append(f"- {ls}")
    prepend.append("\n## Open governance proposals\n- see substrate_calibration/retrospectives/governance_queue.jsonl (human gate)\n")
    PREPEND.write_text("\n".join(prepend) + "\n", encoding="utf-8")

    print(json.dumps({"rubric": rubric, "open_failures": len(open_failures),
                      "recurring": dict(recurring), "cap": cap_line}, indent=2))
    print(f"[retrospect] wrote {PREPEND}")


if __name__ == "__main__":
    main()
